In [1]:
import gym
import numpy as np
from IPython.display import clear_output
import random
import time

In [3]:
env = gym.make("FrozenLake-v1", is_slippery=False)

In [4]:
# Set Hyperparam
learning_rate = 0.1
discount_rate = 0.9
num_episodes = 1000
max_steps_per_episode = 100
debug_model = True

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001

In [ ]:
# Baseline learning

for i_episode in range(num_episodes):
    observation = env.reset()
    for t in range(max_steps_per_episode):
        env.render()
        print(observation)
        action = env.action_space.sample()
        observation, reward, done, info = env.step(action)
        if done:
            print(f"Episode finished after {t+1} timesteps")
            break

env.close()

0
1
Episode finished after 2 timesteps
0
0
4
8
4
8
4
0
4
4
8
4
0
0
4
8
Episode finished after 16 timesteps
0
4
Episode finished after 2 timesteps
0
0
0
0
4
4
Episode finished after 6 timesteps
0
0
0
1
Episode finished after 4 timesteps
0
1
Episode finished after 2 timesteps
0
1
1
0
0
0
4
0
4
8
9
10
14
13
Episode finished after 14 timesteps
0
0
4
4
0
4
0
0
4
0
4
0
0
0
4
8
8
Episode finished after 17 timesteps
0
0
0
0
1
1
1
Episode finished after 7 timesteps
0
0
0
0
0
0
1
0
0
0
0
4
4
Episode finished after 13 timesteps
0
4
8
9
Episode finished after 4 timesteps
0
4
8
4
8
9
13
Episode finished after 7 timesteps
0
4
4
0
0
0
1
2
3
Episode finished after 9 timesteps
0
4
4
0
0
1
0
0
0
1
2
1
0
0
0
0
0
0
0
1
1
2
1
2
3
3
3
3
3
3
3
Episode finished after 31 timesteps
0
1
2
6
2
1
1
0
0
4
0
4
8
Episode finished after 13 timesteps
0
1
0
0
4
Episode finished after 5 timesteps
0
0
1
1
0
4
8
9
13
Episode finished after 9 timesteps
0
4
0
0
4
8
4
4
0
0
1
2
6
2
1
0
0
0
0
0
4
0
1
Episode finished after 23 

In [8]:
# env.observation_space.n
env.action_space.n


4

In [13]:
env.P == env.env.P

True

In [21]:
max_iter = 1000
gamma = 0.9

num_states = env.observation_space.n
num_actions = env.action_space.n
state_prob = env.P

policy = np.zeros(num_states)
values = np.zeros(num_states)

for episode in range(max_iter):
    prev_value = np.copy(values)
    for state in range(num_states):
        q_value = []
        for action in range(num_actions):
            new_state_rewards = []
            for trans_prob, new_state, reward, done in state_prob[state][action]:
                new_state_rewards.append((trans_prob * (reward + gamma * prev_value[new_state])))
        
        q_value.append(sum(new_state_rewards))
        
    values[state] = max(q_value)
    
print(policy[0], episode)

0.0 999


In [24]:
for state in range(num_states):
    q_sa = np.zeros(num_actions)
    for action in range(num_actions):
        for new_state in state_prob[state][action]:
            prob, new_state, reward, done = new_state
            q_sa[action] += (prob * (reward + gamma * values[new_state]))
    
    policy[state] = np.argmax(q_sa)

In [27]:


total_rewards = []

for _ in range(1000):
    current_state = env.reset()
    total_reward = 0
    while True:
        #env.render()
        aciton = policy[current_state]
        new_state, reward, done, _ = env.step(action)
        
        if done:
            total_rewards.append(reward)
            break

print(f"Average rewards: {np.mean(total_rewards)}")

Average rewards: 0.0


In [9]:
action_size = env.action_space.n
state_size = env.observation_space.n
q_table = np.zeros((state_size, action_size))

16


In [27]:
rewards_all_episodes = []

for episode in range(num_episodes):
    
    state = env.reset()
    done = False
    rewards_current_episode = 0
    for step in range(max_steps_per_episode):
        
        exploration_rate_thresh = random.uniform(0, 1)
        if exploration_rate_thresh > exploration_rate:
            action = np.argmax(q_table[state, :])
        else:
            action = env.action_space.sample()
        if debug_model:
            print(f"action: {action}")
            print(f"state: {state}")
        
        new_state, reward, done, info = env.step(action)
        q_table[state, action] = q_table[state, action] * (1 - learning_rate) + \
            learning_rate * (reward + discount_rate *np.max(q_table[new_state, :]))
        state = new_state
        curr_rewards_eps += reward

        if done == True:
            break
            
exploration_rate = min_exploration_rate + (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate * episode)
rewards_all_episodes.append(rewards_current_episode)

action: 3
state: 0
action: 3
state: 0
action: 2
state: 0
action: 1
state: 1
action: 0
state: 0
action: 0
state: 0
action: 2
state: 0
action: 1
state: 0
action: 1
state: 0
action: 1
state: 4
action: 0
state: 4
action: 1
state: 8
action: 1
state: 0
action: 2
state: 0
action: 1
state: 0
action: 1
state: 4
action: 0
state: 4
action: 3
state: 0
action: 0
state: 0
action: 1
state: 4
action: 1
state: 8
action: 1
state: 9
action: 1
state: 13
action: 3
state: 13
action: 3
state: 14
action: 1
state: 0
action: 0
state: 4
action: 3
state: 8
action: 0
state: 4
action: 0
state: 8
action: 3
state: 0
action: 1
state: 0
action: 0
state: 4
action: 2
state: 0
action: 3
state: 0
action: 3
state: 0
action: 2
state: 0
action: 3
state: 4
action: 3
state: 0
action: 1
state: 1
action: 1
state: 2
action: 3
state: 3
action: 2
state: 2
action: 1
state: 2
action: 1
state: 6
action: 2
state: 0
action: 1
state: 4
action: 0
state: 4
action: 3
state: 8
action: 0
state: 8
action: 2
state: 4
action: 0
state: 0
action: 0

action: 2
state: 2
action: 2
state: 3
action: 1
state: 3
action: 3
state: 3
action: 1
state: 3
action: 3
state: 0
action: 0
state: 1
action: 0
state: 1
action: 1
state: 0
action: 0
state: 4
action: 1
state: 4
action: 2
state: 4
action: 2
state: 0
action: 3
state: 0
action: 1
state: 0
action: 0
state: 0
action: 3
state: 0
action: 2
state: 1
action: 3
state: 0
action: 0
state: 0
action: 0
state: 0
action: 0
state: 0
action: 2
state: 4
action: 0
state: 0
action: 0
state: 4
action: 1
state: 4
action: 1
state: 8
action: 1
state: 9
action: 3
state: 8
action: 2
state: 4
action: 3
state: 0
action: 1
state: 1
action: 3
state: 2
action: 3
state: 1
action: 2
state: 0
action: 0
state: 1
action: 3
state: 0
action: 3
state: 0
action: 0
state: 1
action: 2
state: 0
action: 0
state: 0
action: 0
state: 0
action: 1
state: 0
action: 1
state: 4
action: 2
state: 0
action: 1
state: 0
action: 0
state: 0
action: 2
state: 0
action: 2
state: 1
action: 1
state: 1
action: 2
state: 0
action: 2
state: 4
action: 3
st

state: 0
action: 0
state: 1
action: 3
state: 1
action: 1
state: 1
action: 0
state: 0
action: 2
state: 4
action: 1
state: 0
action: 0
state: 1
action: 0
state: 1
action: 1
state: 1
action: 0
state: 0
action: 1
state: 4
action: 3
state: 8
action: 2
state: 8
action: 1
state: 0
action: 1
state: 1
action: 3
state: 0
action: 2
state: 0
action: 2
state: 0
action: 1
state: 4
action: 3
state: 4
action: 3
state: 0
action: 1
state: 0
action: 3
state: 1
action: 3
state: 1
action: 0
state: 1
action: 2
state: 0
action: 1
state: 0
action: 3
state: 4
action: 0
state: 0
action: 2
state: 4
action: 2
state: 0
action: 2
state: 4
action: 2
state: 0
action: 2
state: 4
action: 3
state: 0
action: 2
state: 0
action: 1
state: 4
action: 1
state: 8
action: 1
state: 8
action: 2
state: 8
action: 2
state: 9
action: 3
state: 10
action: 1
state: 9
action: 2
state: 13
action: 1
state: 13
action: 2
state: 14
action: 1
state: 14
action: 3
state: 0
action: 0
state: 0
action: 0
state: 0
action: 0
state: 0
action: 1
state: 

state: 0
action: 0
state: 0
action: 3
state: 4
action: 3
state: 0
action: 0
state: 0
action: 0
state: 0
action: 2
state: 0
action: 1
state: 4
action: 2
state: 8
action: 1
state: 4
action: 3
state: 0
action: 3
state: 1
action: 1
state: 0
action: 1
state: 4
action: 3
state: 0
action: 1
state: 0
action: 0
state: 4
action: 1
state: 4
action: 1
state: 0
action: 3
state: 4
action: 2
state: 0
action: 2
state: 4
action: 1
state: 0
action: 2
state: 1
action: 2
state: 2
action: 0
state: 2
action: 3
state: 2
action: 1
state: 3
action: 3
state: 0
action: 2
state: 1
action: 2
state: 0
action: 3
state: 0
action: 1
state: 1
action: 0
state: 0
action: 3
state: 0
action: 3
state: 0
action: 3
state: 0
action: 2
state: 1
action: 2
state: 2
action: 1
state: 2
action: 2
state: 6
action: 2
state: 2
action: 0
state: 6
action: 1
state: 2
action: 2
state: 3
action: 3
state: 0
action: 3
state: 1
action: 2
state: 2
action: 3
state: 2
action: 3
state: 1
action: 3
state: 0
action: 0
state: 0
action: 2
state: 0
act

action: 0
state: 0
action: 0
state: 4
action: 1
state: 8
action: 0
state: 9
action: 2
state: 8
action: 0
state: 4
action: 1
state: 8
action: 1
state: 9
action: 3
state: 8
action: 1
state: 4
action: 0
state: 0
action: 1
state: 4
action: 2
state: 8
action: 1
state: 4
action: 2
state: 8
action: 0
state: 0
action: 1
state: 4
action: 2
state: 0
action: 2
state: 0
action: 1
state: 4
action: 1
state: 8
action: 3
state: 0
action: 2
state: 0
action: 1
state: 1
action: 0
state: 0
action: 0
state: 4
action: 3
state: 4
action: 2
state: 4
action: 3
state: 0
action: 3
state: 0
action: 2
state: 1
action: 1
state: 1
action: 3
state: 0
action: 2
state: 0
action: 1
state: 1
action: 1
state: 2
action: 1
state: 1
action: 0
state: 2
action: 0
state: 6
action: 3
state: 2
action: 2
state: 1
action: 0
state: 1
action: 1
state: 0
action: 0
state: 0
action: 2
state: 0
action: 2
state: 0
action: 3
state: 1
action: 2
state: 2
action: 2
state: 6
action: 0
state: 2
action: 2
state: 6
action: 2
state: 10
action: 0
s

action: 3
state: 2
action: 0
state: 2
action: 0
state: 2
action: 3
state: 2
action: 0
state: 1
action: 1
state: 0
action: 2
state: 4
action: 0
state: 0
action: 0
state: 4
action: 3
state: 4
action: 3
state: 4
action: 2
state: 4
action: 2
state: 0
action: 1
state: 1
action: 3
state: 0
action: 0
state: 0
action: 3
state: 4
action: 3
state: 0
action: 1
state: 0
action: 2
state: 4
action: 0
state: 0
action: 1
state: 0
action: 3
state: 4
action: 0
state: 0
action: 0
state: 0
action: 2
state: 4
action: 1
state: 0
action: 2
state: 4
action: 3
state: 0
action: 2
state: 0
action: 1
state: 4
action: 1
state: 0
action: 2
state: 4
action: 3
state: 0
action: 2
state: 0
action: 2
state: 1
action: 2
state: 0
action: 2
state: 4
action: 2
state: 0
action: 0
state: 0
action: 2
state: 0
action: 2
state: 1
action: 3
state: 2
action: 2
state: 3
action: 2
state: 3
action: 2
state: 3
action: 3
state: 0
action: 0
state: 0
action: 3
state: 0
action: 1
state: 0
action: 0
state: 0
action: 3
state: 0
action: 2
st

state: 1
action: 2
state: 2
action: 0
state: 3
action: 0
state: 3
action: 2
state: 0
action: 1
state: 1
action: 2
state: 0
action: 0
state: 4
action: 3
state: 4
action: 0
state: 4
action: 3
state: 8
action: 1
state: 4
action: 3
state: 8
action: 0
state: 9
action: 3
state: 8
action: 0
state: 4
action: 1
state: 0
action: 1
state: 1
action: 3
state: 0
action: 3
state: 0
action: 0
state: 0
action: 3
state: 0
action: 1
state: 1
action: 3
state: 0
action: 1
state: 0
action: 0
state: 0
action: 3
state: 0
action: 2
state: 0
action: 1
state: 4
action: 2
state: 4
action: 1
state: 0
action: 0
state: 4
action: 3
state: 8
action: 0
state: 8
action: 1
state: 4
action: 3
state: 4
action: 2
state: 4
action: 0
state: 0
action: 0
state: 0
action: 2
state: 0
action: 0
state: 0
action: 0
state: 0
action: 2
state: 4
action: 3
state: 0
action: 3
state: 0
action: 3
state: 1
action: 2
state: 2
action: 1
state: 2
action: 2
state: 3
action: 2
state: 3
action: 2
state: 0
action: 2
state: 4
action: 3
state: 0
act

action: 2
state: 0
action: 1
state: 4
action: 2
state: 0
action: 1
state: 0
action: 0
state: 1
action: 3
state: 1
action: 0
state: 1
action: 3
state: 1
action: 2
state: 1
action: 3
state: 1
action: 1
state: 2
action: 1
state: 6
action: 2
state: 0
action: 3
state: 0
action: 3
state: 1
action: 3
state: 2
action: 3
state: 2
action: 3
state: 3
action: 0
state: 3
action: 1
state: 2
action: 1
state: 3
action: 0
state: 2
action: 0
state: 1
action: 3
state: 0
action: 0
state: 0
action: 1
state: 0
action: 3
state: 0
action: 3
state: 0
action: 3
state: 1
action: 1
state: 2
action: 0
state: 1
action: 1
state: 1
action: 0
state: 0
action: 3
state: 0
action: 1
state: 0
action: 2
state: 0
action: 1
state: 4
action: 2
state: 0
action: 1
state: 0
action: 0
state: 1
action: 1
state: 0
action: 1
state: 1
action: 0
state: 2
action: 0
state: 1
action: 2
state: 0
action: 1
state: 1
action: 2
state: 2
action: 0
state: 2
action: 2
state: 1
action: 1
state: 2
action: 0
state: 6
action: 1
state: 2
action: 1
st

action: 3
state: 0
action: 3
state: 0
action: 0
state: 1
action: 3
state: 0
action: 1
state: 0
action: 2
state: 4
action: 0
state: 0
action: 1
state: 4
action: 1
state: 4
action: 1
state: 0
action: 3
state: 0
action: 3
state: 1
action: 0
state: 0
action: 0
state: 0
action: 3
state: 4
action: 0
state: 0
action: 0
state: 0
action: 3
state: 0
action: 2
state: 0
action: 1
state: 0
action: 3
state: 4
action: 2
state: 0
action: 3
state: 4
action: 2
state: 0
action: 2
state: 4
action: 1
state: 0
action: 3
state: 1
action: 3
state: 1
action: 1
state: 0
action: 1
state: 0
action: 2
state: 1
action: 1
state: 0
action: 2
state: 4
action: 3
state: 0
action: 2
state: 1
action: 0
state: 2
action: 0
state: 2
action: 0
state: 1
action: 3
state: 1
action: 1
state: 2
action: 0
state: 6
action: 0
state: 0
action: 1
state: 0
action: 1
state: 1
action: 3
state: 0
action: 1
state: 1
action: 0
state: 0
action: 2
state: 0
action: 0
state: 0
action: 3
state: 0
action: 2
state: 0
action: 3
state: 4
action: 1
st

action: 0
state: 0
action: 3
state: 4
action: 1
state: 0
action: 1
state: 1
action: 2
state: 0
action: 2
state: 0
action: 0
state: 4
action: 1
state: 8
action: 3
state: 9
action: 3
state: 0
action: 3
state: 1
action: 3
state: 2
action: 2
state: 1
action: 2
state: 2
action: 1
state: 3
action: 1
state: 3
action: 1
state: 2
action: 3
state: 6
action: 1
state: 0
action: 0
state: 4
action: 0
state: 4
action: 2
state: 4
action: 0
state: 0
action: 3
state: 4
action: 1
state: 0
action: 2
state: 0
action: 1
state: 0
action: 1
state: 0
action: 0
state: 0
action: 1
state: 4
action: 0
state: 8
action: 2
state: 0
action: 3
state: 4
action: 1
state: 0
action: 1
state: 1
action: 3
state: 2
action: 2
state: 2
action: 0
state: 2
action: 0
state: 2
action: 1
state: 1
action: 1
state: 0
action: 3
state: 1
action: 0
state: 0
action: 3
state: 0
action: 3
state: 1
action: 3
state: 2
action: 0
state: 3
action: 1
state: 2
action: 1
state: 6
action: 0
state: 0
action: 3
state: 0
action: 0
state: 0
action: 1
st

action: 0
state: 0
action: 2
state: 0
action: 3
state: 1
action: 1
state: 1
action: 3
state: 0
action: 1
state: 0
action: 2
state: 0
action: 3
state: 0
action: 2
state: 0
action: 0
state: 0
action: 2
state: 4
action: 0
state: 0
action: 3
state: 0
action: 1
state: 0
action: 0
state: 4
action: 2
state: 8
action: 2
state: 0
action: 1
state: 1
action: 3
state: 2
action: 2
state: 3
action: 3
state: 3
action: 3
state: 3
action: 1
state: 2
action: 2
state: 3
action: 1
state: 0
action: 3
state: 0
action: 2
state: 0
action: 1
state: 0
action: 1
state: 1
action: 1
state: 2
action: 1
state: 6
action: 0
state: 0
action: 1
state: 0
action: 1
state: 4
action: 3
state: 0
action: 1
state: 0
action: 2
state: 0
action: 3
state: 1
action: 3
state: 0
action: 0
state: 0
action: 2
state: 0
action: 1
state: 4
action: 3
state: 0
action: 1
state: 1
action: 0
state: 2
action: 1
state: 2
action: 1
state: 6
action: 2
state: 10
action: 1
state: 0
action: 2
state: 4
action: 0
state: 0
action: 1
state: 0
action: 0
s

In [35]:
rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes), num_episodes/1000)

count = 1000
 
print("********1000 에피소드당 평균 reward ********\n")
for r in rewards_per_thousand_episodes:
    print(count, ": ", str(sum(r/1000)))
    count += 1000
    
# 업데이트된 q_table을 출력한다.
print("\n\n********Q_table********\n")
print(q_table)

********1000 에피소드당 평균 reward ********

1000 :  0.0


********Q_table********

[[0.01860938 0.01966661 0.01844462 0.01669237]
 [0.01012598 0.0138246  0.01429668 0.01778768]
 [0.02704048 0.02769423 0.02857738 0.01934975]
 [0.01391074 0.01340698 0.00580495 0.01381625]
 [0.02970544 0.01637493 0.02102578 0.0173324 ]
 [0.         0.         0.         0.        ]
 [0.040472   0.04734941 0.05067678 0.00270909]
 [0.         0.         0.         0.        ]
 [0.01652811 0.03226563 0.03145894 0.0493709 ]
 [0.03923742 0.09475814 0.06458685 0.06468302]
 [0.15945494 0.14983316 0.08430922 0.03416317]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.0474207  0.10644542 0.14973937 0.10734269]
 [0.19695996 0.25417185 0.39773481 0.24224033]
 [0.         0.         0.         0.        ]]


In [36]:
for episode in range(3):
    # 각 에피소드의 변수를 초기화한다.
    state = env.reset()
    done = False
    print("*****에피소드 ", episode+1, "*****\n\n\n\n")
    time.sleep(1)
    for step in range(max_steps_per_episode):
        # 현재 상태를 그려 본다.
        clear_output(wait=True)
        env.render()
        time.sleep(0.3)
        # 현재 상태에서의 q값(보상)이 가장 큰 action을 취한다.
        action = np.argmax(q_table[state, :]) 
        # 새로운 action을 취한다
        new_state, reward, done, info = env.step(action)
        if done:
            if reward == 1:
                # 만약에 Goal에 도착하여 reward가 1이라면
                print("****목표에 도달하였습니다.!****")
                time.sleep(3)
            else:
                # Goal에 도달하지 못했다면
                print("****Hole에 빠지고 말았습니다.****")
                time.sleep(3)
                clear_output(wait=True)            
            break
        
        # 새로운 상태를 설정한다.
        state = new_state

env.close()

****목표에 도달하였습니다.!****


In [ ]:
# part2: value iteration & policy Iteration
# part3: reinforcement learning 
# q-learning